version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/var/www
      - ./apache/web.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8100:80"
